### ISSUE TITLE
Update discord invate URL

### ISSUE THREAD

**Issue by HacKanCuBa** [adamhannigan/sunflower-farmers#11]
The current discord invite URL, which appears [here](https://adamhannigan81.gitbook.io/sunflower-farmers/#community) and [here](https://adamhannigan81.gitbook.io/sunflower-farmers/useful-links), is outdated and invalid. The updated one is `https://discord.gg/RRacudRRkB`

**Comment by adamhannigan** [comment]
@HacKanCuBa Thanks for finding this. We have just updated this.
