### ISSUE TITLE
Game progress only saves in browser. 

### ISSUE THREAD

**Issue by 3s2ng** [adamhannigan/sunflower-farmers#7]
You will lose all SFF token you earned within the 25-minute window if you accidentally close your browser. 

Also if you didn't save within the 25minute window, the timer will continue to negative timer and the gas price is too high. 

![image](https://user-images.githubusercontent.com/200129/131004382-e8e89f22-832d-46b9-ad57-4999f0dced70.png)

**Comment by adamhannigan** [comment]
Great find! This is a frustrating issue and the team is building a better UX to prevent this. @3s2ng 

You can track progress in this issue:
https://github.com/adamhannigan/sunflower-farmers/issues/9
