### ISSUE TITLE
Transaction Error. Exception thrown in contract code.

### ISSUE THREAD

**Issue by R1im** [adamhannigan/sunflower-farmers#8]
Can't upgrade to 11 fields:

![image](https://user-images.githubusercontent.com/7072393/131177065-1da86e80-7a08-4c5c-a321-b473872cc11b.png)

![image](https://user-images.githubusercontent.com/7072393/131177128-ef9f28ad-4fe7-43f9-9c94-1fcf3b60f692.png)

I've seen this error before and it usually goes away in some point, but not this time

**Comment by adamhannigan** [comment]
@R1im Good find! The team is investigating this issue. We believe it is related to the block timestamps conflicting.

**Comment by adamhannigan** [comment]
Given the high gas fees and interaction is similar to #12 we will be closing this issue as fixed for now
